"""The verdict vocabulary, shared by both verification levels.

A reproduction check has one job: tell the person who ran it WHICH KIND of
difference they are looking at, because the kinds have completely different
consequences and only some of them are anybody's fault.

Collapsing this to pass/fail is the failure mode worth designing against. Three
concrete cases from this project's own measurements make the point:

  * A future user on a different GPU/cuDNN/torch will not reproduce our scores
    bit-for-bit. Every logit shifts by a near-constant offset. Nothing is wrong,
    and a check that says FAIL here is a check people learn to ignore.

  * SpoofCeleb/tera correlates with its reference at r = 0.99999 on a maximum
    score difference of 0.043, and its EER still moves 4.15 pp. The scores did
    reproduce; the METRIC did not, because a near-chance model sits where the
    DET curve is flat. That is a caveat about the number, not a defect in the
    run, and it needs its own name or it gets filed as a scoring bug.

  * A cell that scores different utterances than the reference cannot be
    compared by EER at all until the trial sets are reconciled. Reporting "the
    EER moved 6 points" there describes a coverage change in the vocabulary of
    a scoring change.

So the outcome is a LADDER, ordered from strongest agreement to weakest, and
every level names the evidence that placed it there.
"""

__all__ = ["SCORE_LADDER", "ANALYSIS_LADDER", "IS_FAILURE", "rank",
           "worst", "EXACT_TOL", "EER_TOL_PP", "RANK_TOL", "NONFINITE_TOL"]

# --------------------------------------------------------------------------
# Level 1 -- score files
# --------------------------------------------------------------------------

#: Best to worst. `rank()` is an index into this, so ORDER IS THE CONTRACT.
SCORE_LADDER = [
    # The candidate file is byte-for-byte the reference. Nothing else is
    # computed, and nothing else needs to be.
    "IDENTICAL",
    # Same trials, same labels, scores differ, and the EER agrees within
    # EER_TOL_PP. This is what a successful reproduction on different hardware
    # looks like, and it is the target outcome -- not IDENTICAL.
    "EQUIVALENT",
    # Same trials, same labels, scores agree in RANK (spearman >= RANK_TOL) but
    # the EER still moved more than EER_TOL_PP. The flat-DET case. The run is
    # sound; the reported metric is unstable at this operating point. Reported,
    # never failed.
    "SENSITIVE",
    # Trial sets differ. The EER comparison below is computed on the
    # intersection, but the headline numbers are not comparable until the
    # coverage difference is explained.
    "COVERAGE_DIFFERS",
    # Same trials, and the scores genuinely disagree. This is the one that
    # indicts the pipeline: the published column cannot be regenerated by the
    # code that claims to produce it.
    "SCORES_DIFFER",
    # A shared utt_id carries a different key on each side. The protocols are
    # not the same protocol, so every number downstream is meaningless. Fatal
    # for the cell, and it must outrank a mere score difference: comparing
    # scores across disagreeing labels produces a confident wrong answer.
    "LABELS_DIFFER",
    # The candidate wrote NaN/inf beyond tolerance. Its own EER is already
    # unreliable, so no agreement statistic about it means anything.
    "CANDIDATE_INVALID",
    # No candidate file for a cell the reference has.
    "MISSING",
    # The comparison itself raised. Never silently swallowed into a pass.
    "ERROR",
]

# --------------------------------------------------------------------------
# Level 2 -- analysis tables
# --------------------------------------------------------------------------

#: The distinction that matters at this level is not "how big is the delta" but
#: "did a sentence in the paper change". A reproduction can miss every cell by
#: 0.3 pp and still support every claim; it can miss one cell by 0.4 pp and
#: change which model is best. Only the second is a reproduction failure, so
#: the ladder grades on the claims and reports the deltas beside them.
ANALYSIS_LADDER = [
    "IDENTICAL",          # every cell equal to within CELL_TOL_PP
    "EQUIVALENT",         # cells drift, every ranking and every claim survives
    "CONCLUSIONS_HOLD",   # rankings shift among ties, headline claims survive
    "CONCLUSIONS_DIFFER", # a best-in-column, a top-5 set, or a group ordering changed
    "STRUCTURE_DIFFERS",  # different models or columns; cells not comparable
    "MISSING",            # no candidate table
    "ERROR",
]

#: Which verdicts make the run exit non-zero. SENSITIVE and COVERAGE_DIFFERS are
#: deliberately absent: both are real, documented, explainable states, and a
#: gate that fails on them trains people to pass `--ignore`.
IS_FAILURE = {
    "SCORES_DIFFER", "LABELS_DIFFER", "CANDIDATE_INVALID", "MISSING", "ERROR",
    "CONCLUSIONS_DIFFER", "STRUCTURE_DIFFERS",
}

# --------------------------------------------------------------------------
# Thresholds
# --------------------------------------------------------------------------

#: Two scores are "the same number" within this. float32 written as text
#: round-trips at about 1e-7 relative, so this sits well above formatting noise
#: and well below any difference a human would care about.
EXACT_TOL = 1e-6

#: Two cells reproduce each other if their EERs ON THE SAME TRIALS agree within
#: this, in percentage points.
#:
#: This is a tolerance on the METRIC, not on the scores. Individual scores
#: wander far more than this without moving the EER, because EER depends only
#: on how the two class distributions are ordered. Chasing bit-identical scores
#: across GPUs and cuDNN versions is the wrong target; holding the reported
#: number is the right one.
#:
#: 0.05 pp is fifty times the precision the paper prints. It is load-bearing on
#: measured data -- across 190 legacy-vs-v3 cells:
#:
#:     corr >= 0.99999   n=92   median dEER 0.0009 pp   max 4.15 pp
#:     corr <  0.99999   n=79   median dEER 1.6345 pp   max 14.46 pp
#:
#: The five cells in the first row that still exceed 0.05 pp are why SENSITIVE
#: exists as a verdict rather than being folded into a failure.
EER_TOL_PP = 0.05

#: Rank agreement below which scores are held to genuinely disagree rather than
#: to be a monotone remap of each other. EER is rank-based, so Spearman is the
#: quantity a detection claim rests on; Pearson is reported as a diagnostic and
#: never graded, because a constant environment offset destroys it while leaving
#: every decision the model makes unchanged.
RANK_TOL = 0.99

#: Non-finite fraction of the candidate's own scores above which no agreement
#: statistic is trustworthy. Not zero: a handful of NaN in a million-row cell is
#: a corrupt audio file, not a broken pipeline.
NONFINITE_TOL = 0.01

#: Level 2: two table cells agree within this many percentage points. Tighter
#: than EER_TOL_PP because these are recomputations over FIXED score files --
#: arithmetic, not inference -- so the only source of drift is the analysis
#: code itself.
CELL_TOL_PP = 0.005


def rank(verdict, ladder=None):
    """Position on the ladder. Higher is worse. Unknown names sort last."""
    ladder = ladder or SCORE_LADDER
    try:
        return ladder.index(verdict)
    except ValueError:
        return len(ladder)


def worst(verdicts, ladder=None):
    """The worst verdict in a collection, or None if empty."""
    verdicts = list(verdicts)
    if not verdicts:
        return None
    return max(verdicts, key=lambda v: rank(v, ladder))
