"""Compare two score trees, cell by cell, at both levels that matter.

Two trees can disagree for two entirely different reasons, and a single number
cannot tell them apart:

  1. They scored DIFFERENT UTTERANCES.  Coverage grew, a protocol was fixed, a
     dataset was re-segmented.  The EER moves because the trial set moved.
  2. They assigned DIFFERENT SCORES to the SAME UTTERANCES.  Same ids, same
     labels, different numbers.  The EER moves because the model, checkpoint,
     precision, or decoder differed.

The first is a documented change of measurement.  The second is a provenance
problem: it means a published column cannot be regenerated by the pipeline that
claims to produce it.  Reporting only "the EER moved by 6 points" conflates
them, so this tool always reports both.

The separation is made by a third EER, computed on the intersection:

    eer_a          A's own EER, on A's own trials
    eer_b          B's own EER, on B's own trials
    eer_a_common   A's EER restricted to the utterances both trees scored
    eer_b_common   B's EER restricted to the same utterances

`eer_a` vs `eer_a_common` is the effect of coverage alone.  `eer_a_common` vs
`eer_b_common` is the effect of the scores alone, with the trial set held
fixed -- it is the only one of the four comparisons that can indict the
pipeline, and it is the one a reproducibility claim rests on.

Output is one CSV row per (dataset, model) cell plus a JSON summary.  Nothing
is written to either tree.

This is the AD-HOC tool: point it at any two trees and read the result. To
check a tree against the PUBLISHED reference -- and to check the analysis
tables that come out of it -- use `python -m spoof_superb.verification`, which
grades on the shared ladder and writes a report. Both share the measurement
code in `verification.cells`; only the verdict vocabulary differs.

Usage
-----
    python -m spoof_superb.tools.compare_trees \\
        --a /data/ssl_anti_spoofing/asd_superb_score_files      --a-layout legacy \\
        --b /data/ssl_anti_spoofing/spoof_superb_score_files    --b-layout v3 \\
        --out outputs/tree_comparison
"""

import argparse
import csv
import json
from pathlib import Path

from spoof_superb.verification.cells import (DATASETS, cell_paths, compare_cell,
                                             eer_pct, rewrite_components,
                                             strip_absolute_prefix)
from spoof_superb.verification.verdicts import EER_TOL_PP, EXACT_TOL

#: Kept under its original name: this tool's vocabulary predates the shared
#: ladder in `verification.verdicts` and its tests name this constant.
REPRODUCE_TOL_PP = EER_TOL_PP

__all__ = ["DATASETS", "cell_paths", "compare_cell", "eer_pct",
           "rewrite_components", "strip_absolute_prefix", "verdict",
           "REPRODUCE_TOL_PP", "EXACT_TOL", "main"]


def verdict(row):
    """Classify the cell by WHY it differs, and whether the difference matters.

    The grading is on the EER over the shared trials, because that is the
    quantity the paper reports and the only one a reproduction claim is about.
    A cell whose individual scores all moved but whose EER did not has
    reproduced the published result; a cell whose EER moved has not, however
    well its scores correlate.
    """
    if row["n_common"] == 0:
        return "no overlap"
    if row["label_mismatch"]:
        return "LABELS DIFFER"

    same_trials = row["n_only_a"] == 0 and row["n_only_b"] == 0
    coverage = "" if same_trials else " + coverage"

    if row["frac_exact"] == 1.0:
        return "identical" if same_trials else "coverage only"

    a, b = row["eer_a_common"], row["eer_b_common"]
    if a is None or b is None:
        return "not comparable" + coverage
    if abs(a - b) <= REPRODUCE_TOL_PP:
        return "reproduces" + coverage
    return "SCORES DIFFER" + coverage


FIELDS = ["dataset", "model", "status", "n_a", "n_b", "n_common", "n_only_a",
          "n_only_b", "dup_a", "dup_b", "nan_a", "nan_b", "label_mismatch",
          "max_abs_diff", "corr", "frac_exact", "prefix_a", "prefix_b",
          "eer_a", "eer_b",
          "eer_a_common", "eer_b_common", "d_eer_common", "verdict", "missing"]


def main(argv=None):
    ap = argparse.ArgumentParser(prog="python -m spoof_superb.tools.compare_trees",
                                 description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--a", required=True, help="first score tree (the reference)")
    ap.add_argument("--b", required=True, help="second score tree")
    ap.add_argument("--a-layout", required=True, choices=("legacy", "v2", "v3"))
    ap.add_argument("--b-layout", required=True, choices=("legacy", "v2", "v3"))
    ap.add_argument("--out", required=True, help="output directory")
    ap.add_argument("--models", nargs="*", default=None,
                    help="score-file slugs (default: the paper roster)")
    ap.add_argument("--datasets", nargs="*", default=None,
                    help="display names (default: all benchmark columns)")
    ap.add_argument("--a-id-rewrite", nargs="*", default=None, metavar="OLD=NEW",
                    help="rename whole path components in A's utt_ids, e.g. "
                         "-=Bonafide for Famous Figures. Asserts that the two "
                         "conventions name the same utterances.")
    ap.add_argument("--b-id-rewrite", nargs="*", default=None, metavar="OLD=NEW",
                    help="the same, for B's utt_ids")
    args = ap.parse_args(argv)

    from spoof_superb.scoring.models import paper_models
    slugs = args.models or sorted(paper_models())
    wanted = ([d for d in DATASETS if d[0] in set(args.datasets)]
              if args.datasets else DATASETS)

    def parse_rules(pairs):
        if not pairs:
            return {}
        out = {}
        for p in pairs:
            if "=" not in p:
                ap.error(f"--*-id-rewrite expects OLD=NEW, got {p!r}")
            old, new = p.split("=", 1)
            out[old] = new
        return out

    rewrite_a = parse_rules(args.a_id_rewrite)
    rewrite_b = parse_rules(args.b_id_rewrite)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"A = {args.a}  (layout={args.a_layout})")
    print(f"B = {args.b}  (layout={args.b_layout})")
    print(f"{len(wanted)} datasets x {len(slugs)} models = "
          f"{len(wanted) * len(slugs)} cells\n", flush=True)

    rows = []
    for disp, key in wanted:
        for slug in slugs:
            r = {"dataset": disp, "model": slug}
            try:
                r.update(compare_cell(cell_paths(args.a_layout, args.a, key, slug),
                                      cell_paths(args.b_layout, args.b, key, slug),
                                      rewrite_a, rewrite_b))
                if r.get("status") == "ok":
                    r["verdict"] = verdict(r)
            except Exception as exc:            # a cell must not kill the sweep
                r.update({"status": "error", "verdict": "error",
                          "missing": f"{type(exc).__name__}: {exc}"})
            if r.get("eer_a_common") is not None and r.get("eer_b_common") is not None:
                r["d_eer_common"] = abs(r["eer_a_common"] - r["eer_b_common"])
            rows.append(r)
            print(f"  {disp:<11} {slug:<40} {r.get('verdict', r['status'])}",
                  flush=True)

    csv_path = out_dir / "cell_comparison.csv"
    with open(csv_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=FIELDS, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)

    tally = {}
    for r in rows:
        tally[r.get("verdict", r["status"])] = tally.get(r.get("verdict", r["status"]), 0) + 1

    scored = [r for r in rows if r.get("d_eer_common") is not None]
    summary = {
        "a": {"root": args.a, "layout": args.a_layout},
        "b": {"root": args.b, "layout": args.b_layout},
        "cells": len(rows),
        "verdicts": tally,
        "worst_common_eer_gap": sorted(
            ({"dataset": r["dataset"], "model": r["model"],
              "eer_a_common": r["eer_a_common"], "eer_b_common": r["eer_b_common"],
              "d": r["d_eer_common"], "corr": r.get("corr")}
             for r in scored),
            key=lambda d: -d["d"])[:20],
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2))

    print("\n=== VERDICTS ===")
    for k, v in sorted(tally.items(), key=lambda kv: -kv[1]):
        print(f"  {k:<28} {v}")
    print(f"\nWrote {csv_path}")
    print(f"Wrote {out_dir / 'summary.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
