"""Compare two score trees, cell by cell, at both levels that matter.

Two trees can disagree for two entirely different reasons, and a single number
cannot tell them apart:

  1. They scored DIFFERENT UTTERANCES.  Coverage grew, a protocol was fixed, a
     dataset was re-segmented.  The EER moves because the trial set moved.
  2. They assigned DIFFERENT SCORES to the SAME UTTERANCES.  Same ids, same
     labels, different numbers.  The EER moves because the model, checkpoint,
     precision, or decoder differed.

The first is a documented change of measurement.  The second is a provenance
problem: it means a published column cannot be regenerated by the pipeline that
claims to produce it.  Reporting only "the EER moved by 6 points" conflates
them, so this tool always reports both.

The separation is made by a third EER, computed on the intersection:

    eer_a          A's own EER, on A's own trials
    eer_b          B's own EER, on B's own trials
    eer_a_common   A's EER restricted to the utterances both trees scored
    eer_b_common   B's EER restricted to the same utterances

`eer_a` vs `eer_a_common` is the effect of coverage alone.  `eer_a_common` vs
`eer_b_common` is the effect of the scores alone, with the trial set held
fixed -- it is the only one of the four comparisons that can indict the
pipeline, and it is the one a reproducibility claim rests on.

Output is one CSV row per (dataset, model) cell plus a JSON summary.  Nothing
is written to either tree.

Usage
-----
    python -m spoof_superb.tools.compare_trees \\
        --a /data/ssl_anti_spoofing/asd_superb_score_files      --a-layout legacy \\
        --b /data/ssl_anti_spoofing/spoof_superb_score_files    --b-layout v3 \\
        --out outputs/tree_comparison
"""

import argparse
import csv
import json
import os
import sys
from pathlib import Path

import numpy as np

from spoof_superb.core.metrics import compute_eer
from spoof_superb.core.scorefile import read_scored
from spoof_superb.core.scorepath import mlaad_pool_paths, score_path

#: Benchmark columns, as (display name, registry key).  MLAAD is pooled from two
#: corpora and is resolved separately; everything else is one file per layout.
DATASETS = [
    ("ASV19 LA",   "eval_2019"),
    ("ASV21 LA",   "asvspoof2021_LA"),
    ("ASV21 DF",   "asvspoof2021_DF"),
    ("ASV5 Eval",  "asvspoof5"),
    ("ITW",        "wild"),
    ("DFEval24",   "deepfake_eval_2024"),
    ("FF",         "Famous_Figures"),
    ("ASVLD",      "asvspoofLD"),
    ("SpoofCeleb", "spoofceleb"),
    ("MLAAD",      "Multilingual"),
]

#: Legacy has no per-dataset directory convention for linear_head, so its paths
#: are built the way the pre-reorganisation code built them.
LEGACY_ASVLD_EXTRA = ("asvld_rerun", "Recompression", "linear_head_Recompression_{slug}.txt")

#: DFEval24 is a different measurement under v2/v3: every 4 s window rather than
#: one window per recording.  Comparing them is meaningful only as coverage.
DATASET_KEY_BY_LAYOUT = {
    "deepfake_eval_2024": {"v2": "deepfake_eval_2024_segmented",
                           "v3": "deepfake_eval_2024_segmented"},
}

#: Scores equal to within this are treated as the same number.  float32 score
#: files round-trip through text at about 1e-7 relative, so this is well above
#: formatting noise and well below any real difference.
EXACT_TOL = 1e-6

#: Two cells REPRODUCE each other if their EERs on the same trials agree to
#: within this, in percentage points.
#:
#: Not a tolerance on the scores -- individual scores wander by far more than
#: this without moving the EER, because EER depends only on the ordering of the
#: two class distributions, not on the values.  Chasing bit-identical scores
#: across GPUs, cuDNN versions and batch sizes is the wrong target; holding the
#: reported metric is the right one.
#:
#: 0.05 pp is fifty times the precision the paper prints (3 decimals).  On the
#: measured legacy-vs-v3 data the threshold IS load-bearing, and the reason is
#: worth knowing: score agreement and EER agreement are not the same question,
#: and for near-chance models they come apart badly.
#:
#:     corr >= 0.99999   n=92   median dEER 0.0009 pp   max 4.15 pp
#:     corr <  0.99999   n=79   median dEER 1.6345 pp   max 14.46 pp
#:
#: Five cells have essentially perfect score correlation and still move the EER
#: by more than 0.05 pp -- SpoofCeleb/tera moves 4.15 pp on a maximum score
#: difference of 0.043.  Those are models operating near chance, where the DET
#: curve is flat at the crossing point, so a hair's movement in the scores
#: reorders a large number of trials.  It is not a parsing artefact: it is what
#: an unstable operating point looks like, and it is a caveat on reporting a
#: three-decimal EER for a model that cannot separate the classes.
#:
#: So the verdict grades on the EER, which is what a reproduction claim is
#: about, and the CSV carries `corr` and `max_abs_diff` beside it so the two
#: questions stay separable.
REPRODUCE_TOL_PP = 0.05


def cell_paths(layout, root, dataset, slug):
    """Every score file composing one (dataset, model) cell, in pool order."""
    if dataset == "Multilingual":
        return [Path(p) for p in mlaad_pool_paths(slug, scores_root=root,
                                                  layout=layout)]
    if layout == "legacy":
        paths = [Path(root) / "linear_head" / f"linear_head_{dataset}_{slug}.txt"]
        if dataset == "asvspoofLD":
            a, b, c = LEGACY_ASVLD_EXTRA
            paths.append(Path(root) / a / b / c.format(slug=slug))
        return paths
    key = DATASET_KEY_BY_LAYOUT.get(dataset, {}).get(layout, dataset)
    return [Path(score_path("linear_head", key, slug, scores_root=root,
                            layout=layout))]


def eer_pct(labels, scores):
    """EER in percent, or None if either class is empty or all-NaN."""
    finite = ~np.isnan(scores)
    labels, scores = labels[finite], scores[finite]
    bona = scores[labels == "bonafide"]
    spoof = scores[labels == "spoof"]
    if bona.size == 0 or spoof.size == 0:
        return None
    return 100.0 * compute_eer(bona, spoof)[0]


def strip_absolute_prefix(utts):
    """Make ids corpus-relative by removing a shared absolute directory prefix.

    Famous Figures score files in the old tree record ids as ABSOLUTE paths
    (`/nfs/turbo/.../famousfigures/Anthony_Blinken/...`) while the new tree
    records them relative to the corpus root. They are the same utterances, but
    compared literally the intersection is empty -- so all 19 FF cells reported
    "no overlap", which reads as "these trees share no trials" when the truth is
    "one of them wrote the mount point into every id".

    Narrow on purpose: only a prefix that is ABSOLUTE and common to every id in
    the file is removed. Relative ids are never touched, so a genuine coverage
    difference can never be normalised away into a false match.

    Returns (ids, prefix_removed).
    """
    if utts.size == 0 or not str(utts[0]).startswith("/"):
        return utts, ""
    prefix = os.path.commonprefix(utts.tolist())
    prefix = prefix[:prefix.rindex("/") + 1] if "/" in prefix else ""
    if not prefix.startswith("/"):
        return utts, ""
    n = len(prefix)
    return np.asarray([u[n:] for u in utts.tolist()], dtype=object), prefix


def rewrite_components(utts, rules):
    """Rename whole path components in every id.  `rules` is {old: new}.

    Kept out of `strip_absolute_prefix` and off by default, because unlike a
    shared absolute prefix this cannot be detected -- it has to be asserted. The
    case it exists for is Famous Figures, where the old tree names the bonafide
    directory ``-`` and the new one names it ``Bonafide``:

        Anthony_Blinken/-/Anthony_Blinken_00001.wav
        Anthony_Blinken/Bonafide/Anthony_Blinken_00001.wav

    Same utterance, different convention. Without the rewrite the bonafide half
    of every FF cell fails to align, the intersection is all-spoof, and the cell
    reports as "not comparable" -- true, but it hides that the spoof half
    matched perfectly.

    Requiring it on the command line keeps the claim "these are the same
    utterances" a stated assumption rather than a silent one.
    """
    if not rules:
        return utts
    return np.asarray(
        ["/".join(rules.get(c, c) for c in u.split("/")) for u in utts.tolist()],
        dtype=object)


def compare_cell(paths_a, paths_b, rewrite_a=None, rewrite_b=None):
    """Both comparison levels for one cell.  Returns a dict, or None if absent.

    Alignment is by utt_id.  A duplicated utt_id within one tree would make the
    intersection ill-defined, so it is counted and reported rather than silently
    resolved by last-write-wins.
    """
    missing_a = [p for p in paths_a if not p.exists()]
    missing_b = [p for p in paths_b if not p.exists()]
    if missing_a or missing_b:
        return {"status": "missing_a" if missing_a else "missing_b",
                "missing": str((missing_a or missing_b)[0])}

    utt_a, lab_a, sc_a = read_scored(paths_a)
    utt_b, lab_b, sc_b = read_scored(paths_b)
    utt_a, pre_a = strip_absolute_prefix(utt_a)
    utt_b, pre_b = strip_absolute_prefix(utt_b)
    utt_a = rewrite_components(utt_a, rewrite_a)
    utt_b = rewrite_components(utt_b, rewrite_b)

    dup_a = utt_a.size - len(set(utt_a.tolist()))
    dup_b = utt_b.size - len(set(utt_b.tolist()))

    # Index A, then walk B once.  Keeps one tree's worth of ids in memory
    # instead of two, which matters for the 2M-row ASVLD cells.
    index_a = {u: i for i, u in enumerate(utt_a.tolist())}
    idx_a, idx_b = [], []
    for j, u in enumerate(utt_b.tolist()):
        i = index_a.get(u)
        if i is not None:
            idx_a.append(i)
            idx_b.append(j)
    idx_a = np.asarray(idx_a, dtype=np.int64)
    idx_b = np.asarray(idx_b, dtype=np.int64)

    row = {
        "status": "ok",
        "n_a": int(utt_a.size),
        "n_b": int(utt_b.size),
        "n_common": int(idx_a.size),
        "n_only_a": int(utt_a.size - idx_a.size),
        "n_only_b": int(utt_b.size - idx_b.size),
        "dup_a": int(dup_a),
        "dup_b": int(dup_b),
        "prefix_a": pre_a,
        "prefix_b": pre_b,
        "nan_a": int(np.isnan(sc_a).sum()),
        "nan_b": int(np.isnan(sc_b).sum()),
        "eer_a": eer_pct(lab_a, sc_a),
        "eer_b": eer_pct(lab_b, sc_b),
    }

    if idx_a.size == 0:
        row.update({"label_mismatch": None, "max_abs_diff": None, "corr": None,
                    "frac_exact": None, "eer_a_common": None,
                    "eer_b_common": None, "verdict": "no overlap"})
        return row

    ca_lab, cb_lab = lab_a[idx_a], lab_b[idx_b]
    ca_sc, cb_sc = sc_a[idx_a], sc_b[idx_b]
    row["label_mismatch"] = int((ca_lab != cb_lab).sum())

    both = ~np.isnan(ca_sc) & ~np.isnan(cb_sc)
    x, y = ca_sc[both], cb_sc[both]
    if x.size:
        d = np.abs(x - y)
        row["max_abs_diff"] = float(d.max())
        row["frac_exact"] = float((d <= EXACT_TOL).mean())
        # A constant column has zero variance and no defined correlation; that
        # is a real condition (a dead model), not an error.
        row["corr"] = (float(np.corrcoef(x, y)[0, 1])
                       if x.std() > 0 and y.std() > 0 else None)
    else:
        row.update({"max_abs_diff": None, "frac_exact": None, "corr": None})

    row["eer_a_common"] = eer_pct(ca_lab, ca_sc)
    row["eer_b_common"] = eer_pct(cb_lab, cb_sc)
    row["verdict"] = verdict(row)
    return row


def verdict(row):
    """Classify the cell by WHY it differs, and whether the difference matters.

    The grading is on the EER over the shared trials, because that is the
    quantity the paper reports and the only one a reproduction claim is about.
    A cell whose individual scores all moved but whose EER did not has
    reproduced the published result; a cell whose EER moved has not, however
    well its scores correlate.
    """
    if row["n_common"] == 0:
        return "no overlap"
    if row["label_mismatch"]:
        return "LABELS DIFFER"

    same_trials = row["n_only_a"] == 0 and row["n_only_b"] == 0
    coverage = "" if same_trials else " + coverage"

    if row["frac_exact"] == 1.0:
        return "identical" if same_trials else "coverage only"

    a, b = row["eer_a_common"], row["eer_b_common"]
    if a is None or b is None:
        return "not comparable" + coverage
    if abs(a - b) <= REPRODUCE_TOL_PP:
        return "reproduces" + coverage
    return "SCORES DIFFER" + coverage


FIELDS = ["dataset", "model", "status", "n_a", "n_b", "n_common", "n_only_a",
          "n_only_b", "dup_a", "dup_b", "nan_a", "nan_b", "label_mismatch",
          "max_abs_diff", "corr", "frac_exact", "prefix_a", "prefix_b",
          "eer_a", "eer_b",
          "eer_a_common", "eer_b_common", "d_eer_common", "verdict", "missing"]


def main(argv=None):
    ap = argparse.ArgumentParser(prog="python -m spoof_superb.tools.compare_trees",
                                 description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--a", required=True, help="first score tree (the reference)")
    ap.add_argument("--b", required=True, help="second score tree")
    ap.add_argument("--a-layout", required=True, choices=("legacy", "v2", "v3"))
    ap.add_argument("--b-layout", required=True, choices=("legacy", "v2", "v3"))
    ap.add_argument("--out", required=True, help="output directory")
    ap.add_argument("--models", nargs="*", default=None,
                    help="score-file slugs (default: the paper roster)")
    ap.add_argument("--datasets", nargs="*", default=None,
                    help="display names (default: all benchmark columns)")
    ap.add_argument("--a-id-rewrite", nargs="*", default=None, metavar="OLD=NEW",
                    help="rename whole path components in A's utt_ids, e.g. "
                         "-=Bonafide for Famous Figures. Asserts that the two "
                         "conventions name the same utterances.")
    ap.add_argument("--b-id-rewrite", nargs="*", default=None, metavar="OLD=NEW",
                    help="the same, for B's utt_ids")
    args = ap.parse_args(argv)

    from spoof_superb.scoring.models import paper_models
    slugs = args.models or sorted(paper_models())
    wanted = ([d for d in DATASETS if d[0] in set(args.datasets)]
              if args.datasets else DATASETS)

    def parse_rules(pairs):
        if not pairs:
            return {}
        out = {}
        for p in pairs:
            if "=" not in p:
                ap.error(f"--*-id-rewrite expects OLD=NEW, got {p!r}")
            old, new = p.split("=", 1)
            out[old] = new
        return out

    rewrite_a = parse_rules(args.a_id_rewrite)
    rewrite_b = parse_rules(args.b_id_rewrite)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"A = {args.a}  (layout={args.a_layout})")
    print(f"B = {args.b}  (layout={args.b_layout})")
    print(f"{len(wanted)} datasets x {len(slugs)} models = "
          f"{len(wanted) * len(slugs)} cells\n", flush=True)

    rows = []
    for disp, key in wanted:
        for slug in slugs:
            r = {"dataset": disp, "model": slug}
            try:
                r.update(compare_cell(cell_paths(args.a_layout, args.a, key, slug),
                                      cell_paths(args.b_layout, args.b, key, slug),
                                      rewrite_a, rewrite_b))
            except Exception as exc:            # a cell must not kill the sweep
                r.update({"status": "error", "verdict": "error",
                          "missing": f"{type(exc).__name__}: {exc}"})
            if r.get("eer_a_common") is not None and r.get("eer_b_common") is not None:
                r["d_eer_common"] = abs(r["eer_a_common"] - r["eer_b_common"])
            rows.append(r)
            print(f"  {disp:<11} {slug:<40} {r.get('verdict', r['status'])}",
                  flush=True)

    csv_path = out_dir / "cell_comparison.csv"
    with open(csv_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=FIELDS, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)

    tally = {}
    for r in rows:
        tally[r.get("verdict", r["status"])] = tally.get(r.get("verdict", r["status"]), 0) + 1

    scored = [r for r in rows if r.get("d_eer_common") is not None]
    summary = {
        "a": {"root": args.a, "layout": args.a_layout},
        "b": {"root": args.b, "layout": args.b_layout},
        "cells": len(rows),
        "verdicts": tally,
        "worst_common_eer_gap": sorted(
            ({"dataset": r["dataset"], "model": r["model"],
              "eer_a_common": r["eer_a_common"], "eer_b_common": r["eer_b_common"],
              "d": r["d_eer_common"], "corr": r.get("corr")}
             for r in scored),
            key=lambda d: -d["d"])[:20],
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2))

    print("\n=== VERDICTS ===")
    for k, v in sorted(tally.items(), key=lambda kv: -kv[1]):
        print(f"  {k:<28} {v}")
    print(f"\nWrote {csv_path}")
    print(f"Wrote {out_dir / 'summary.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
